package uz.elmurod.newsapi.buildSrc

object Versions {
    const val gradle_version = "7.0.2"
    const val kotlin_version = "1.5.31"
    const val hilt_version = "2.38.1"
    const val compile_sdk_version = 31
    const val build_tools_version = "30.0.3"
    const val min_sdk_version = 21
    const val target_sdk_version = 30
    const val lifecycle_version = "2.4.0"
    const val fragment_version = "1.3.6"
    const val paging_version = "3.0.1"
    const val material_version = "1.5.0-alpha04"
    const val core_ktx_version = "1.6.0"
    const val appcompat_version = "1.3.1"
    const val constraint_layout_version = "2.1.0"
    const val legacy_support_version = "1.0.0"
    const val recyclerView_version = "1.1.0"
    const val card_view_version = "1.0.0"
    const val multiDex_version = "2.0.1"
    const val reflect_version = "1.5.31"
    const val glide_version = "4.12.0"
    const val retrofit_version = "2.9.0"
    const val chucker_version = "3.3.0"
    const val otp_view_version = "v1.1.2-ktx"
    const val location_version = "17.1.0"
    const val shimmer_version = "0.5.0"
    const val lottie_version = "4.1.0"
    const val navigation_version = "2.3.5"
    const val google_services_version = "4.3.10"
    const val room_version = "2.3.0"
    const val play_core_version = "1.8.1"
    const val camerax_version = "1.0.0-beta10"
    const val camera_view_version = "1.0.0-alpha17"
    const val ok_http_version = "4.9.0"
    const val compressor_version = "3.0.0"
    const val dynamic_animation_version = "1.0.0"
    const val auth_service_version = "19.0.0"
    const val auth_api_version = "17.5.0"
    const val coroutines_version = "1.5.2"
    const val moshi_version = "1.12.0"
    const val binding_version = "1.4.4"
    const val circle_image_view_version = "3.1.0"
    const val firebase_bom_version = "28.4.0"
    const val swipe_refresh_version = "1.1.0"
    const val data_store_version = "1.0.0"
    const val map_kit_lite_version = "4.0.0-lite"
    const val motion_layout_version = "2.0.4"
    const val view_pager_2_version = "1.0.0"
    const val pluto_version = "1.0.8"
    const val toasty_version = "1.5.2"
    const val socket_io_version = "2.0.1"


    //testImplementations
    const val jj_unit = "4.13.2"
    const val j_unit = "1.1.3"
    const val espresso_core = "3.4.0"
}